FROM golang:1.12

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN mkdir -p /go/src/github.com/devops-israel/global-forward-auth
WORKDIR /go/src/github.com/devops-israel/global-forward-auth

ADD . /go/src/github.com/devops-israel/global-forward-auth
#RUN make deps
# RUN make build_inside_docker
CMD ["bash"]