global-forward-auth:
  build: .
  command: tail -f /dev/null
  dockerfile: Dockerfile.development
  volumes:
    - .:/go/src/github.com/devops-israel/global-forward-auth
  ports:
    - "9292:9292"
    - "2345:2345"
  expose:
    - "2345"
    - "9292"
